name: Testing

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches:  [ "master" ]

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                java-version: "17"
                distribution: "temurin"
                cache: maven
            - name: Run Test
              run: mvn test allure:report
            - name: Export test results as a tar file
              if: always()
              run: tar -cvf allure-results.tar ./target/allure-results/
            - name: Archieve test artifacts
              uses: actions/upload-artifact@v3
              with:
                name: allure-results
                path: allure-results.tar